ALTER TABLE zapsign_contratos
  ADD COLUMN IF NOT EXISTS demanda TEXT,
  ADD COLUMN IF NOT EXISTS fase TEXT,
  ADD COLUMN IF NOT EXISTS valor_contrato NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS pagamento_inicial BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS boleto_emitido BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS observacoes TEXT;
